TA/TAApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from application.views import application_view
from InstructorAddCourse.views import instructor_add_course_view
from adminSummary.views import admin_summary_view, send_email, edit_course, delete_course, show_applications
from instructorSummary.views import instructor_summary_view, instructor_show_applications, approve_application, reject_application
from studentSummary.views import student_summary_view, apply_course, edit_application, delete_application, accept_application, decline_application
from login.views import  login_home, logout, register, welcome


urlpatterns = [
    path("admin/", admin.site.urls),
    path('', welcome, name= 'welcome'),
    path('login/', include("django.contrib.auth.urls")),
    path('login/', include('login.urls')),
    #path('logout/', logout, name = 'logout'),
    path('register/', register, name = 'register'),
    path('application/', application_view),
    path('add_course/', instructor_add_course_view, name = 'add_course'),
    path('admin_summary/', admin_summary_view),
    path('instructor_summary/', instructor_summary_view),
    path('student_summary/', student_summary_view),
    path('send_email/', send_email, name = 'send_email'),
    path("edit_course/<int:course_id>/", edit_course, name="edit_course"),
    path("apply_course/<int:course_id>/", apply_course, name="apply_course"),
    path("edit_application/<int:application_id>/", edit_application, name="edit_application"),
    path('delete_course/<int:course_id>/', delete_course, name='delete_course'),
    path('delete_application/<int:application_id>/', delete_application, name='delete_application'),
    path('show_applications/', show_applications, name='show_applications'),
    path('instructor_show_applications/', instructor_show_applications, name='instructor_show_applications'),
    path('approve_application/<int:application_id>/', approve_application, name='approve_application'),
    path('reject_application/<int:application_id>/', reject_application, name='reject_application'),
    path('accept_application/<int:application_id>/', accept_application, name='accept_application'),
    path('decline_application/<int:application_id>/', decline_application, name='decline_application'),



]

TA/adminSummary/models.py
from django.db import models

# Create your models here.

TA/instructorSummary/models.py
from django.db import models

# Create your models here.

TA/studentSummary/models.py
from django.db import models

# Create your models here.

TA/application/forms.py
from django import forms
from .models import Application

class ApplicationForm(forms.ModelForm):


    class Meta:
        model = Application
        fields = ('course_name','course_number', 'description','first_name', 'last_name', 'eagle_id', 'grad','past_course', 'grade', 'hours', 'other_courses', 'misc_information')
        widgets = {

            
            'past_course': forms.RadioSelect(attrs={'class': 'form-check-input'}),
            'grade': forms.Select(attrs={'class': 'form-select'}),
            'grad': forms.Select(attrs={'class': 'form-select'}),
            'hours': forms.NumberInput(attrs={'class': 'form-control', 'min': 0}),
            'other_courses': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'misc_information': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }
    
    def __init__(self, *args, **kwargs):
        super(ApplicationForm, self).__init__(*args, **kwargs)

        self.fields['course_name'].label = "Course Name"
        self.fields['course_number'].label = "Course Number"
        self.fields['description'].label = "Description"
        self.fields['other_courses'].required = False
        self.fields['misc_information'].required = False
        self.fields['past_course'].label = 'Have you taken this course in the past?'
        self.fields['grade'].label = 'If so, what grade did you receive'
        self.fields['hours'].label = 'How many hours can you commit to the position?'
        self.fields['other_courses'].label = 'What other relevant courses have you taken?'
        self.fields['misc_information'].label = 'Answers to extra questions, misc. information'
        self.fields['first_name'].label = 'First name'
        self.fields['last_name'].label = 'Last name'
        self.fields['eagle_id'].label = 'Eagle ID'
        self.fields['grad'].label = 'Graduation year'
        # self.fields['course_name'].required = False
        # self.fields['course_number'].required = False
        # self.fields['description'].required = False

TA/login/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from .models import CustomUser


# Define choices for the role field
ROLE_CHOICES = [   
   ('S', 'Student'),   
   ('T', 'Teacher'),   
   ('A', 'Admin'),
]


# Define choices for the major field
MAJOR_CHOICES = [
   ('NA', 'NA'),
   ('BA', 'Bachelor of Arts in Computer Science'),
   ('BS', 'Bachelor of Science in Computer Science'),
   ('Minor', 'Computer Science Minor'),
]


# Define choices for the cohort field
YEAR_CHOICES = [
   ('NA', 'NA'),
   ('2026', '2026'),
   ('2025', '2025'),
   ('2024', '2024'),
   ('2023', '2023'),
]


class CustomAuthenticationForm(AuthenticationForm):
   role = forms.CharField()


   def __init__(self, *args, **kwargs):
       super().__init__(*args, **kwargs)
       self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Username'})
       self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Password'})
       


   def clean(self):
       cleaned_data = super().clean()
       role = cleaned_data.get('role')
       if not role:
           raise forms.ValidationError('Role is required.')
       return cleaned_data




# Create a custom registration form that includes the role field
class RegistrationForm(UserCreationForm):
   role = forms.ChoiceField(choices=ROLE_CHOICES)
   first_name = forms.CharField(max_length = 20, required = True)
   last_name = forms.CharField(max_length = 20, required = True)
   major = forms.ChoiceField(choices=MAJOR_CHOICES, required=False)
   eagle_id = forms.CharField(max_length=8, required=False)
   year = forms.ChoiceField(choices=YEAR_CHOICES, required=False)
   email = forms.EmailField(max_length=254, required=True)


   def clean(self):
       cleaned_data = super().clean()
       role = cleaned_data.get('role')
       first_name = cleaned_data.get('first_name')
       last_name = cleaned_data.get('last_name')
       major = cleaned_data.get('major')
       eagle_id = cleaned_data.get('eagle_id')
       year = cleaned_data.get('year')


       if role == 'S':
           if (major == 'NA' or not eagle_id or year == 'NA'):
               raise forms.ValidationError("Please fill out all required fields for student registration")
           
       if (not first_name or not last_name):
           raise forms.ValidationError("Please fill out the fields First Name and Last Name")


       return cleaned_data


   class Meta(UserCreationForm.Meta):
       model = CustomUser
       fields = ['username', 'password1', 'password2', 'role', 'first_name', 'last_name', 'major', 'eagle_id', 'year','email']

TA/adminSummary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.core.mail import send_mail
from InstructorAddCourse.models import InstructorAddCourse
from application.models import Application


def get_term(course):
    return course.term


def get_dept(course):
    dept_code = ""
    for i in course.course_number:
        if i.isalpha():
            dept_code = "".join([dept_code, i])
    return dept_code


def get_status(course):
    return "Open" if course.curr_num_ta < course.num_ta_needed else "Closed"


term_keys = InstructorAddCourse.objects.values_list(
    'term', flat=True).distinct()
dept_keys = sorted(list(set([get_dept(course)
                   for course in InstructorAddCourse.objects.all()])))
status_keys = ['Open', 'Closed']


def admin_summary_view(response):
    search_query = response.GET.get('q', '')
    term_filter = response.GET.get('term', '')
    status_filter = response.GET.get('status', '')
    dept_filter = response.GET.get('dept-code', '')

    course_objects = InstructorAddCourse.objects.all()
    applied_filters = []
    if search_query:
        course_objects = course_objects.filter(
            course_name__icontains=search_query)
        applied_filters.append(('q', search_query))

    if term_filter:
        if term_filter in term_keys:
            course_objects = [course for course in course_objects if get_term(
                course) == term_filter]
            applied_filters.append(('term', term_filter))

    if dept_filter:
        if dept_filter in dept_keys:
            course_objects = [course for course in course_objects if get_dept(
                course) == dept_filter]
            applied_filters.append(('dept-code', dept_filter))

    if status_filter:
        if status_filter in status_keys:
            course_objects = [course for course in course_objects if get_status(
                course) == status_filter]
            applied_filters.append(('status', status_filter))
    else:
        applied_filters = [f for f in applied_filters if f[0] != 'status']

    applications = []
    if 'course_number' in response.session:
        course_number = response.session['course_number']
        applications = Application.objects.filter(course_number=course_number).exclude(student_response='A')
        del response.session['course_number']

    course_count = len(course_objects)
    context = {'course_objects': course_objects,
               'course_count': course_count, 'applied_filters': applied_filters,
               'term_keys': term_keys, 'dept_keys': dept_keys,
               'applications': applications}

    return render(response, "adminSummary.html", context)


def show_applications(request):
    if request.method == "POST":
        course_number = request.POST['course_number']
        request.session['course_number'] = course_number
        return redirect(admin_summary_view)
    else:
        return redirect(admin_summary_view)


def send_email(response):
    send_mail(
        'Example Subject',
        'Example message.',
        'swe2023testing@gmail.com',
        ['yangbam@bc.edu'],
        fail_silently=False,
    )
    return redirect(admin_summary_view)


def edit_course(request, course_id):
    course = get_object_or_404(InstructorAddCourse, id=course_id)
    if request.method == "POST":
        course.course_name = request.POST['course_name']
        course.course_number = request.POST['course_number']
        course.course_instructor = request.POST['course_instructor']
        course.description = request.POST['description']
        course.total_time_commitment = request.POST['total_time_commitment']
        course.has_discussion = request.POST['has_discussion']
        course.num_ta_needed = request.POST['num_ta_needed']
        course.curr_num_ta = request.POST['curr_num_ta']
        course.graded_meeting = request.POST['graded_meeting']
        course.office_hours = request.POST['office_hours']
        course.other_info = request.POST['other_info']
        course.term = request.POST['term']

        course.save()
        return redirect(request.session.get('previous_url', '/'))
    else:
        request.session['previous_url'] = request.META.get('HTTP_REFERER', '/')
        return render(request, "edit_course.html", {"course": course})


def delete_course(request, course_id):
    course = get_object_or_404(InstructorAddCourse, id=course_id)
    course.delete()
    # return redirect(admin_summary_view)
    return redirect(request.session.get('previous_url', '/'))

TA/application/views.py
from django.shortcuts import render
from .forms import ApplicationForm
from django.contrib import messages
from login.models import CustomUser
from application.models import Application
from django.contrib.auth.decorators import login_required


@login_required
def application_view(request):
    if request.method == 'POST':
        form = ApplicationForm(request.POST)
        if form.is_valid():
            user = CustomUser.objects.get(id=request.user.id)
            if user.can_apply():
                user.increment_applications()
                user.save()

                application = form.save(commit=False)
                application.student = request.user
                application.save()
                return render(request, 'success.html')
            else:
                form.add_error(None, "You have already applied to 5 courses (maximum number of applications)")
        else:
            
            form = ApplicationForm()
        return render(request, 'application.html', {'form': form})
    else:
        form = ApplicationForm()
    return render(request, 'application.html', {'form': form})

TA/instructorSummary/views.py
from django.shortcuts import render, redirect, get_object_or_404
from InstructorAddCourse.models import InstructorAddCourse
from django.contrib.auth.models import User
from application.models import Application
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.core.mail import send_mail

def get_term(course):
    return course.term


def get_dept(course):
    dept_code = ""
    for i in course.course_number:
        if i.isalpha():
            dept_code = "".join([dept_code, i])
    return dept_code

def get_status(course):
    return "Open" if course.curr_num_ta < course.num_ta_needed else "Closed"


@login_required
def instructor_summary_view(response):
    search_query = response.GET.get('q', '')
    term_filter = response.GET.get('term', '')
    status_filter = response.GET.get('status', '')
    dept_filter = response.GET.get('dept-code', '')

    current_user = response.user
    course_objects = InstructorAddCourse.objects.filter(course_instructor=current_user)

    term_keys = course_objects.values_list('term', flat=True).distinct()
    dept_keys = sorted(list(set([get_dept(course)
                   for course in course_objects])))
    status_keys = sorted(list(set([get_status(course)
                   for course in course_objects])))


    applied_filters = []
    if search_query:
        course_objects = course_objects.filter(
            course_name__icontains=search_query)
        applied_filters.append(('q', search_query))

    if term_filter and term_filter in term_keys:
        course_objects = course_objects.filter(term=term_filter)
        applied_filters.append(('term', term_filter))

    if dept_filter and dept_filter in dept_keys:
        course_objects = course_objects.filter(course_number__istartswith=dept_filter)
        applied_filters.append(('dept-code', dept_filter))

    if status_filter and status_filter in status_keys:
        course_objects = [course for course in course_objects if get_status(course) == status_filter]
        applied_filters.append(('status', status_filter))

    else:
        applied_filters = [f for f in applied_filters if f[0] != 'status']

    applications = []
    if 'course_number' in response.session:
        course_number = response.session['course_number']
        applications = Application.objects.filter(course_number=course_number)
        del response.session['course_number']

    course_count = len(course_objects)
    context = {'course_objects': course_objects,
               'course_count': course_count, 'applied_filters': applied_filters,
               'term_keys': term_keys, 'dept_keys': dept_keys,
               'applications': applications}

    return render(response, "instructorSummary.html", context)

def instructor_show_applications(request):
    if request.method == "POST":
        course_number = request.POST['course_number']
        request.session['course_number'] = course_number
        return redirect(instructor_summary_view)
    else:
        return redirect(instructor_summary_view)

@require_POST
def approve_application(request, application_id):
    request.session['previous_url'] = request.META.get('HTTP_REFERER', '/')
    application = get_object_or_404(Application, id=application_id)
    application.is_approved = True
    application.save()

    send_email([application.student.email], application.course_name)

    return redirect(request.session.get('previous_url', '/'))

@require_POST
def reject_application(request, application_id):
    request.session['previous_url'] = request.META.get('HTTP_REFERER', '/')
    application = get_object_or_404(Application, id=application_id)
    application.is_rejected = True
    application.save()

    send_email([application.student.email], application.course_name)

    return redirect(request.session.get('previous_url', '/'))

def send_email(recipients, course_name):
    send_mail(
        'Your application has been approved!',
        'Congratulations! Your application for the course {} has been approved. Please accept/decline the request in your portal.'.format(course_name),
        'swe2023testing@gmail.com',
        recipients,
        fail_silently=False,
    )
    return redirect(instructor_summary_view)

TA/templates/addCoursePage.html
<!DOCTYPE html>
{% extends 'appbase.html' %} {% block content %} {% load static %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'application.css' %}" />
    <title>Add Course</title>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col offset-md-3">
          <div class="form-group">
              <form method="post">
                {% csrf_token %}
                <h2 class="border-bottom border-2 border-dark mb-4">
                  Instructor Add Course
                </h2>
                <p class="mb-4">
                  Please Enter Info Below
                </p>
                {% if user.role == 'A' %}
                  <div class="form-group mb-4">
                    <label for="professor_name">Professor:</label>
                    <input type="text" class="form-control" id="professor_name" name="professor_name">
                  </div>
                {% else %}
                  <h6 class="mb-4">
                    Professor: {{ user.first_name }} {{ user.last_name}}
                  </h6>
                {% endif %}
                <div class="form-group mb-4">
                  {{ form.course_name.label_tag }} {{ form.course_name }}
                </div>

                <div class="form-group mb-4">
                  {{ form.course_number.label_tag }} {{ form.course_number }}
                </div>

                <div class="form-group mb-4">
                  {{ form.description.label_tag }} {{ form.description }}
                </div>
                <!-- <div class="form-group mb-4">
                  {{ form.course_instructor.label_tag }} {{ form.course_instructor }}
                </div> -->

                <input type="hidden" name="course_instructor" value="{{ user.last_name }}">

                <div class="form-group mb-4">
                  {{ form.course_description.label_tag }} {{ form.course_description }}
                </div>

                <div class="form-group mb-4">
                  {{ form.total_time_commitment.label_tag }} {{ form.total_time_commitment }}
                </div>

                <div class="form-group mb-4">
                  {{ form.has_discussion.label_tag }} {% for radio in form.has_discussion %}
                  <div class="form-check">{{ radio }}</div>
                  {% endfor %}
                </div>

                <div class="form-group mb-4">
                  {{ form.num_ta_needed.label_tag }} {{ form.num_ta_needed }}
                </div>


                <div class="form-group mb-4">
                  {{ form.graded_meeting.label_tag }} {% for radio in form.graded_meeting %}
                  <div class="form-check">{{ radio }}</div>
                  {% endfor %}
                </div>

                <div class="form-group mb-4">
                  {{ form.office_hours.label_tag }} {{ form.office_hours }}
                </div>
                

                <div class="form-group mb-4">
                  {{ form.other_info.label_tag }} {{ form.other_info}}
                </div>

                <button type="submit" class="btn btn-primary btn-block mb-4">
                  Submit
                </button>

              </form>
            </div>
        </div>
      </div>
    </div>
  </body>
</html>

{% endblock %}

TA/templates/admin_home.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <title>Admin Home</title>
</head>
<body>
    <header>
<h2 style="color:brown"><center>Welcome to the TA Application HomePage!</center>
</header>
<main>
    {% block title %}Admin Home{% endblock %}
    {% if user.is_authenticated %}
        Hello {{ user.username}}!
        <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
    {% endif %}
</main>
</body>
</html>

TA/templates/admin_success.html
<h1>Success! Your application has been submitted<h1>
    <a href="http://127.0.0.1:8000/admin_summary/">Back to Home Page</a>

TA/templates/appbase.html
{% load static %}
<html>
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'appbase.css' %}" />
  </head>

  <body>
    <div class="container-fluid m-4">
      {% if messages %}
        {% for message in messages %}
          
          <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div>

        {% endfor %}
      {% endif %}
      <div class="row m-3">
        <div class="col-sm">
          <div class="container-fluid d-flex justify-content-end">
            <a class="nav-link btn btn-sm sign-out-button" href="{% url 'logout' %}">Sign Out</a>
          </div>
        </div>
        </div>
        <div class="row m-3">
          {% block content %} {% endblock %}
        </div>
      </div>
  </body>
</html>

TA/templates/application.html
<!DOCTYPE html>
{% extends 'appbase.html' %} {% block content %} {% load static %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'application.css' %}" />
    <title>Applying to a Course</title>
  </head>


  <body>

    <div class="container">
      <div class="row">
        <div class="col offset-md-3">
          <div class="form-group">

              <form method="post">
                {% csrf_token %}

                <h2 class="border-bottom border-2 border-dark mb-4">
                  {{ course.course_name }} {{ course.course_number }}
                </h2>
                <h6 class="mb-4">
                  Professor: {{ course.course_instructor}}
                </h6>
                <p class="mb-4">
                  Course Description: {{ course.description }}
                </p>
                <h5 class="mb-4">
                  Available positions: {{course.num_ta_needed}}
                </h5>

                </p>
                </h7 class="mb-4">
                  First Name: {{user.first_name}}
                </h7>
                </p>
                </h8 class="mb-4">
                  Last Name: {{user.last_name}}
                </h8>
                </p>
                </h8 class="mb-4">
                  Eagle ID: {{user.eagle_id}}
                </h8>
                </p>
                </h8 class="mb-4">
                  Grad Year: {{user.year}}
                </h8>
                </p>


                {% if form.errors %}
                <div class="alert alert-danger">
                    {% for field, errors in form.errors.items %}
                        <strong>{{ field|title }}:</strong>
                        {% for error in errors %}
                            {{ error }}
                        {% endfor %}
                    {% endfor %}
                </div>
            {% endif %}
            
           
            <!-- <div class="form-group mb-4">
              {{ form.course_name.label_tag }} {{ form.course_name }}
            </div>
            <div class="form-group mb-4">
              {{ form.course_number.label_tag }} {{ form.course_number }}
            </div>
            <div class="form-group mb-4">
              {{ form.description.label_tag }} {{ form.description }}
            </div> -->


            <input type="hidden" name="course_name" value="{{ course.course_name }}">
            <input type="hidden" name="course_number" value="{{ course.course_number }}">
            <input type="hidden" name="description" value="{{ course.description }}">

            <input type="hidden" name="first_name" value="{{user.first_name}}">
            <input type="hidden" name="last_name" value="{{user.last_name}}">
            <input type="hidden" name="eagle_id" value="{{user.eagle_id}}">
            <input type="hidden" name="grad" value="{{user.year}}">


                
                <div class="form-group mb-4">
                  {{ form.past_course.label_tag }} {% for radio in form.past_course %}
                  <div class="form-check">{{ radio }}</div>
                  {% endfor %}
                </div>
                <div class="form-group mb-4">
                  {{ form.grade.label_tag }} {{ form.grade }}
                </div>
                <div class="form-group mb-4">
                  {{ form.hours.label_tag }} {{ form.hours }}
                </div>
                <div class="form-group mb-4">
                  {{ form.other_courses.label_tag }} {{ form.other_courses }}
                </div>
                <div class="form-group mb-4">
                  {{ form.misc_information.label_tag }} {{ form.misc_information}}
                </div>
                <button type="submit" class="btn btn-primary btn-block mb-4">
                  Submit
                </button>
              </form>
            </div>
        </div>
      </div>
    </div>
  </body>
</html>
{% endblock %}

TA/templates/instructor_success.html
<h1>Success! Your Course has been submitted<h1>


    {% if user.role == 'A' %}
    <a href="https://techsupport-production.up.railway.app/admin_summary/">Back to Home Page</a>
  {% endif %}
  
  {% if user.role == 'T' %}
  <a href="https://techsupport-production.up.railway.app/instructor_summary/">Back to Home Page</a>
{% endif %}

TA/templates/register.html
{% load static %}
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous"/>
    <link rel="stylesheet" href="{% static 'register.css' %}"/>
</head>
<body>
<div class="container register-container">
    <div class="row mb-4">
        <div class="col-12 text-center">
            <h2>Register</h2>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-12 col-md-8">
            <form action="" method="POST" id="register-form">
                {% csrf_token %}
                {% for field in form %}
                <div class="form-group row {% if field.name in hidden_fields %}d-none{% endif %}">
                    <label for="{{ field.id_for_label }}" class="col-sm-5 col-form-label text-right">{{ field.label }}</label>
                    <div class="col-sm-7">
                        {{ field }}
                        {% if field.errors %}
                        <div class="alert alert-danger mt-2">
                            {{ field.errors|first }}
                        </div>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
                <div class="row justify-content-center">
                    <button type="submit" class="btn btn-primary col-6 col-md-4 mt-3">Register</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function () {
        var roleSelect = document.querySelector('#id_role');
        var hiddenFields = ['id_eagle_id', 'id_major', 'id_year'];

        function toggleFields() {
            var selectedRole = roleSelect.value;
            var formGroups = document.querySelectorAll('.form-group');
            hiddenFields.forEach(function (fieldId) {
                var fieldGroup = document.querySelector('#' + fieldId).closest('.form-group');
                if (selectedRole === 'T' || selectedRole === 'A') {
                    fieldGroup.classList.add('d-none');
                } else {
                    fieldGroup.classList.remove('d-none');
                }
            });
        }

        toggleFields();

        roleSelect.addEventListener('change', function () {
            toggleFields();
        });
    });
</script>

</body>
</html>

TA/templates/student_home.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <title>Student Home</title>
</head>
<body>
    <header>
<h2 style="color:brown"><center>Welcome to the TA Application HomePage!</center>
</header>
<main>
    {% block title %}Student Home{% endblock %}
    {% if user.is_authenticated %}
        Hello {{ user.username}}!
        <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
    {% endif %}
</main>
</body>
</html>

TA/templates/teacher_home.html
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <title>Teacher Home</title>
</head>
<body>
    <header>
<h2 style="color:brown"><center>Welcome to the TA Application HomePage!</center>
</header>
<main>
    {% block title %}Teacher Home{% endblock %}
    {% if user.is_authenticated %}
        Hello {{ user.username}}!
        <p><a href="{% url 'logout' %}">Log Out</a></p>
    {% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
    {% endif %}
</main>
</body>
</html>